# graph/database.py
# Stores topology snapshots and alerts in a SQLite database.
#
# WHY A DATABASE INSTEAD OF JUST JSON FILES?
#
# topology.json is a snapshot — it only shows the current state.
# A database gives you HISTORY — you can ask:
#   "What did the topology look like 2 hours ago?"
#   "How many alerts happened this week?"
#   "When did R7 first go offline?"
#
# We use SQLite because:
#   - It's a single file (topology.db) — no server needed
#   - Perfect for a project of this scale
#   - SQLAlchemy lets us write Python instead of raw SQL
#
# SQLAlchemy is an ORM (Object Relational Mapper).
# ORM means you define Python classes and SQLAlchemy
# automatically creates and queries the database tables for you.
# You never write raw SQL unless you want to.
#
# DATABASE SCHEMA:
#
#   devices table          connections table        alerts table
#   ─────────────          ─────────────────        ────────────
#   id (PK)                id (PK)                  id (PK)
#   device_id              from_device              alert_type
#   hostname               to_device                message
#   ip                     from_if                  details (JSON)
#   tier                   to_if                    timestamp
#   description            srtt_ms                  acknowledged
#   snapshot_time          mac
#                          snapshot_time
#
# Each time the collector runs, a new set of rows is inserted
# with the current snapshot_time as the timestamp.

import sys
sys.stdout.reconfigure(encoding='utf-8')

import json
from datetime import datetime
from sqlalchemy import (
    create_engine, Column, Integer, String,
    Float, Boolean, DateTime, Text
)
from sqlalchemy.orm import declarative_base, Session
from config.settings import DATABASE_URL

# Base class — all our table models inherit from this
Base = declarative_base()


# ── Table Definitions (Models) ────────────────────────────────────────────

class DeviceRecord(Base):
    """
    One row per device per snapshot.
    Each collector run inserts fresh rows with the current timestamp.
    """
    __tablename__ = "devices"

    id            = Column(Integer, primary_key=True, autoincrement=True)
    device_id     = Column(String, nullable=False)   # "R1", "SWL2" etc
    hostname      = Column(String)
    ip            = Column(String)
    tier          = Column(String)
    description   = Column(Text)
    snapshot_time = Column(DateTime, default=datetime.utcnow)


class ConnectionRecord(Base):
    """
    One row per connection per snapshot.
    """
    __tablename__ = "connections"

    id            = Column(Integer, primary_key=True, autoincrement=True)
    from_device   = Column(String, nullable=False)
    to_device     = Column(String, nullable=False)
    from_if       = Column(String)
    to_if         = Column(String)
    srtt_ms       = Column(Integer)
    mac           = Column(String)
    neighbour_ip  = Column(String)
    snapshot_time = Column(DateTime, default=datetime.utcnow)


class AlertRecord(Base):
    """
    One row per alert generated by the change detector.
    Alerts persist until acknowledged by an operator.
    """
    __tablename__ = "alerts"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    alert_type   = Column(String, nullable=False)  # NEW_DEVICE, LOST_LINK etc
    message      = Column(String, nullable=False)
    details      = Column(Text)                    # JSON string
    timestamp    = Column(DateTime, default=datetime.utcnow)
    acknowledged = Column(Boolean, default=False)


# ── Database Setup ────────────────────────────────────────────────────────

def get_engine():
    """Create and return the SQLAlchemy engine."""
    return create_engine(DATABASE_URL, echo=False)


def init_db():
    """
    Create all tables if they don't exist yet.
    Safe to call multiple times — won't overwrite existing data.
    """
    engine = get_engine()
    Base.metadata.create_all(engine)
    return engine


# ── Write Functions ───────────────────────────────────────────────────────

def save_snapshot(topology: dict):
    """
    Save a complete topology snapshot to the database.
    Inserts new rows for all devices and connections.
    Old rows are kept — this builds up history over time.
    """
    engine = init_db()
    snapshot_time = datetime.utcnow()

    with Session(engine) as session:
        # Save devices
        for device in topology.get("devices", []):
            record = DeviceRecord(
                device_id     = device["id"],
                hostname      = device.get("hostname", ""),
                ip            = device.get("ip", ""),
                tier          = device.get("tier", ""),
                description   = device.get("description", ""),
                snapshot_time = snapshot_time
            )
            session.add(record)

        # Save connections
        for conn in topology.get("connections", []):
            record = ConnectionRecord(
                from_device   = conn["from"],
                to_device     = conn["to"],
                from_if       = conn.get("from_if", ""),
                to_if         = conn.get("to_if", ""),
                srtt_ms       = int(conn.get("srtt_ms", 0) or 0),
                mac           = conn.get("mac", ""),
                neighbour_ip  = conn.get("neighbour_ip", ""),
                snapshot_time = snapshot_time
            )
            session.add(record)

        # Save alerts
        for alert in topology.get("alerts", []):
            record = AlertRecord(
                alert_type = alert["type"],
                message    = alert["message"],
                details    = json.dumps(alert.get("details", {})),
                timestamp  = datetime.fromisoformat(alert["timestamp"])
            )
            session.add(record)

        session.commit()
        print(f"  ✓ Snapshot saved to database ({snapshot_time.strftime('%H:%M:%S')})")


# ── Read Functions ────────────────────────────────────────────────────────

def get_latest_devices() -> list:
    """
    Return the most recent snapshot of all devices.
    Finds the latest snapshot_time and returns only those rows.
    """
    engine = init_db()
    with Session(engine) as session:
        # Find the most recent snapshot time
        latest = session.query(DeviceRecord.snapshot_time)\
                        .order_by(DeviceRecord.snapshot_time.desc())\
                        .first()
        if not latest:
            return []

        records = session.query(DeviceRecord)\
                         .filter(DeviceRecord.snapshot_time == latest[0])\
                         .all()

        return [
            {
                "device_id": r.device_id,
                "hostname":  r.hostname,
                "ip":        r.ip,
                "tier":      r.tier,
                "snapshot":  r.snapshot_time.isoformat()
            }
            for r in records
        ]


def get_latest_connections() -> list:
    """Return the most recent snapshot of all connections."""
    engine = init_db()
    with Session(engine) as session:
        latest = session.query(ConnectionRecord.snapshot_time)\
                        .order_by(ConnectionRecord.snapshot_time.desc())\
                        .first()
        if not latest:
            return []

        records = session.query(ConnectionRecord)\
                         .filter(ConnectionRecord.snapshot_time == latest[0])\
                         .all()

        return [
            {
                "from":     r.from_device,
                "to":       r.to_device,
                "srtt_ms":  r.srtt_ms,
                "mac":      r.mac,
                "snapshot": r.snapshot_time.isoformat()
            }
            for r in records
        ]


def get_unacknowledged_alerts() -> list:
    """Return all alerts that haven't been acknowledged yet."""
    engine = init_db()
    with Session(engine) as session:
        records = session.query(AlertRecord)\
                         .filter(AlertRecord.acknowledged == False)\
                         .order_by(AlertRecord.timestamp.desc())\
                         .all()

        return [
            {
                "id":         r.id,
                "type":       r.alert_type,
                "message":    r.message,
                "details":    json.loads(r.details),
                "timestamp":  r.timestamp.isoformat(),
                "acknowledged": r.acknowledged
            }
            for r in records
        ]


def acknowledge_alert(alert_id: int):
    """Mark a specific alert as acknowledged."""
    engine = init_db()
    with Session(engine) as session:
        record = session.query(AlertRecord).filter(AlertRecord.id == alert_id).first()
        if record:
            record.acknowledged = True
            session.commit()
            print(f"  ✓ Alert {alert_id} acknowledged")
        else:
            print(f"  [WARN] Alert {alert_id} not found")


def get_snapshot_count() -> int:
    """Return total number of snapshots stored."""
    engine = init_db()
    with Session(engine) as session:
        from sqlalchemy import func
        result = session.query(
            func.count(DeviceRecord.snapshot_time.distinct())
        ).scalar()
        return result or 0


# ── quick test ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import os
    from config.settings import TOPOLOGY_OUTPUT_PATH

    # Load current topology.json and save to database
    print("Initialising database...")
    init_db()
    print("  ✓ Tables created")

    # Load topology and save snapshot
    with open(TOPOLOGY_OUTPUT_PATH, "r", encoding="utf-8") as f:
        topology = json.load(f)

    print("Saving topology snapshot to database...")
    save_snapshot(topology)

    # Read back and verify
    print("\nReading back from database...")
    devices     = get_latest_devices()
    connections = get_latest_connections()
    alerts      = get_unacknowledged_alerts()

    print(f"\n── Database Contents ───────────────────────────────")
    print(f"  Devices:      {len(devices)}")
    print(f"  Connections:  {len(connections)}")
    print(f"  Alerts:       {len(alerts)}")
    print(f"  Snapshots:    {get_snapshot_count()}")

    print(f"\n── Latest Devices ──────────────────────────────────")
    for d in devices:
        print(f"  {d['device_id']:8s} {d['ip']:18s} {d['tier']}")

    print(f"\n── Latest Connections ──────────────────────────────")
    for c in connections:
        print(f"  {c['from']:8s} ↔ {c['to']:8s}  srtt={c['srtt_ms']}ms")

    if alerts:
        print(f"\n── Unacknowledged Alerts ───────────────────────────")
        for a in alerts:
            print(f"  [{a['type']}] {a['message']}")